In [1]:
import pyreadr, pandas as pd
res = pyreadr.read_r('./gr_network_human_21122021.rds')

In [4]:
gr_df = res[None]

In [7]:
gr_df

,from,to,source,database
0,KLF2,DLGAP1,harmonizome_CHEA,harmonizome_gr
1,KLF2,DTNB,harmonizome_CHEA,harmonizome_gr
2,KLF2,BHLHE40,harmonizome_CHEA,harmonizome_gr
3,KLF2,RPS6KA1,harmonizome_CHEA,harmonizome_gr
4,KLF2,PXN,harmonizome_CHEA,harmonizome_gr
...,...,...,...,...
5870445,H2BC10,ITGA2B,pathwaycommons_controls_expression_of,pathwaycommons_expression
5870446,H2BC10,KDM4B,pathwaycommons_controls_expression_of,pathwaycommons_expression
5870447,H2BC10,KLK2,pathwaycommons_controls_expression_of,pathwaycommons_expression
5870448,H2BC10,KLK3,pathwaycommons_controls_expression_of,pathwaycommons_expression
5870449,H2BC10,MYC,pathwaycommons_controls_expression_of,pathwaycommons_expression

In [8]:
edges = gr_df[['from', 'to']].copy()  
# A. 人にも読める TSV（サイズは大きめ）
edges.to_csv('tf_target_edges.tsv', sep='\t', index=False)

In [2]:
import pyreadr, pandas as pd
res = pyreadr.read_r('/home/suzuki/Projects/scDiffusion/external_data/gr_network_mouse_21122021.rds')
gr_df = res[None]

In [3]:
gr_df

            from          to                source        database
0         Arid3a        A1bg    harmonizome_ENCODE  harmonizome_gr
1           Atf4        A1bg  harmonizome_TRANSFAC  harmonizome_gr
2        Bhlhe40        A1bg    harmonizome_ENCODE  harmonizome_gr
3         Cacybp        A1bg  harmonizome_TRANSFAC  harmonizome_gr
4          Cebpd        A1bg      harmonizome_CHEA  harmonizome_gr
...          ...         ...                   ...             ...
5574289     Klf4  Dnmt3b-ps1     regnetwork_source      regnetwork
5574290    Nanog  Dnmt3b-ps1     regnetwork_source      regnetwork
5574291     Olr1  Dnmt3b-ps1  harmonizome_GEO_GENE  harmonizome_gr
5574292    Pcgf2  Dnmt3b-ps1     regnetwork_source      regnetwork
5574293   Tfap2c  Dnmt3b-ps1                trrust          trrust

[5574294 rows x 4 columns]

In [4]:
edges = gr_df[['from', 'to']].copy()  
# A. 人にも読める TSV（サイズは大きめ）
edges.to_csv('/home/suzuki/Projects/scDiffusion/external_data/Mouse_tf_target_edges.tsv', sep='\t', index=False)